import numpy as np 
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
b = np.delete(a,1)
print(a)
print(b)
c = np.delete(a,[1,3])
print(a)
print(c)
d = np.delete(a,-1)
print(a)
print(d)
e = np.delete(a,np.s_[1:3])
print(a)
print(e)