import numpy as np 
print("Iterieren")
a = np.arange(0,30)
b = np.array_split(a,2)
print(b, type(b), type(b[0]))
c=np.array(b)
print(c, c.shape)
d = np.array_split(c,3, axis=1)
print(d)
e=np.array(d)
print(e, e.shape)
